" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2019 Jan 26
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings, bail
" out.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  if has('persistent_undo')
    set undofile	" keep an undo file (undo changes after closing)
  endif
endif

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif

execute pathogen#infect()

let g:airline_powerline_fonts = 1
let g:airline_theme = 'raven'

set number
set nolist
set listchars=eol:$,space:.,tab:▒░,trail:▓,nbsp:░
" set list

set tabstop=4
set shiftwidth=4
set expandtab

nmap <F9> :tabp<CR>
nmap <F10> :tabn<CR>
nmap <S-F9> :AirlineToggle<CR>
nmap <F2> :tabe<SPACE>
nmap <F3> :noh<CR>
nmap <S-F5> :last<CR>
nmap <S-F10> :set cursorcolumn!<CR>

set omnifunc=syntaxcomplete#Complete

filetype plugin on
syntax on

set colorcolumn=80
set cursorline
" set cursorcolumn
autocmd ColorScheme *
     \ highlight cursorline term=bold cterm=bold ctermbg=238 |
     \ highlight cursorcolumn term=bold cterm=bold ctermbg=238 |
     \ highlight colorcolumn ctermbg=238

colorscheme delek
" colorscheme nord
" colorscheme monokai 
" if $COLORTERM != ""
"     hi Normal guibg=NONE ctermbg=NONE
"     set termguicolors
" endif
" removes trailing whitespaces
" autocmd BufWritePre * %s/\s\+$//e

source ~/.vim/vimrc_coc
